insert into phone(p_id, name) values(1, 'iPhone 13');
insert into phone(p_id, name) values(2, 'iPhone 13 Pro');
insert into phone(p_id, name) values(3, 'iPhone 13 Pro Max');
insert into phone(p_id, name) values(4, 'iPhone 13 Mini');
insert into phone(p_id, name) values(5, 'iPhone SE');
insert into manufacturer(m_id, name) values(1, 'Apple');
insert into phone_manufacturer(m_id, p_id) values(1, 1);
insert into phone_manufacturer(m_id, p_id) values(1, 2);
insert into phone_manufacturer(m_id, p_id) values(1, 3);
insert into phone_manufacturer(m_id, p_id) values(1, 4);
insert into phone_manufacturer(m_id, p_id) values(1, 5);
insert into phone(p_id, name) values(6, 'Galaxy S22');
insert into phone(p_id, name) values(7, 'Galaxy S22 Plus');
insert into phone(p_id, name) values(8, 'Galaxy S22 Ultra');
insert into manufacturer(m_id, name) values(2, 'Samsung');
insert into phone_manufacturer(m_id, p_id) values(2, 6);
insert into phone_manufacturer(m_id, p_id) values(2, 7);
insert into phone_manufacturer(m_id, p_id) values(2, 8);
insert into phone(p_id, name) values(9, 'Pixel 6');
insert into phone(p_id, name) values(10, 'Pixel 6 Pro');
insert into manufacturer(m_id, name) values(3, 'Google');
insert into phone_manufacturer(m_id, p_id) values(3, 9);
insert into phone_manufacturer(m_id, p_id) values(3, 10);
insert into phone(p_id, name) values(11, 'One Plus 10 Pro');
insert into manufacturer(m_id, name) values(4, 'One Plus');
insert into phone_manufacturer(m_id, p_id) values(4, 11);